.model small
.stack 100H
.data
    ;Texts that will be printed on the screen
    ;-----------------------------------  
        ; MENU
        TETRIS  db 15, ' T E T R I S ', 15,'$'
        PLAY db '(S)start$'
        EXIT  db '(E)exit$'
        DESIGN db 'Developed by Alexei Klimovich, 2022$'
    
        ; GAME LAYOUT
        BLOCK equ 00DBh ; ASCII Character Û One BLOCK = One CHAR
        GAME_SIDE_VERTICAL  db BLOCK, '          ', BLOCK,'$'
        GAME_FIELD_GORIZONT db 12 dup(BLOCK), '$'
        PIECE_BOX_BASE db 8 dup(BLOCK), '$'
        PART_BOX_SIDE db BLOCK, '      ', BLOCK,'$'
        SCORE_MSG db 'SCORE$'

        ; FUGURES
        FIGURE_T db ' ',BLOCK,'  $',BLOCK,BLOCK,BLOCK,' $','    $','    $'
        FIGURE_S db ' ',BLOCK,BLOCK,' $',BLOCK,BLOCK,'  $','    $','    $'
        FIGURE_Z db BLOCK,BLOCK,'  $',' ',BLOCK,BLOCK,' $','    $','    $'
        FIGURE_I db '    $',BLOCK,BLOCK,BLOCK,BLOCK,'$','    $','    $'
        FIGURE_O db ' ',BLOCK,BLOCK,' $',' ',BLOCK,BLOCK,' $','    $','    $'
        FIGURE_J db BLOCK,'   $',BLOCK,BLOCK,BLOCK,' ','$','    $','    $'
        FIGURE_L db '  ',BLOCK,' $',BLOCK,BLOCK,BLOCK,' $','    $','    $'
        
        ; FINAL SCREEN
        THANKS db 'T H A N K  Y O U$F O R  P L A Y I N G$'
       
        ; GAME OVER SCREEN
        GAME db 'G A M E$'
        OVER db 'O V E R$'

    
    ;  Game Variables
    ;------------------------------------
        GAME_SCORE dw ?
        NEXT_FIGURE_NUM db ?
        CURR_FIGURE_NUM db ?
        CURR_W db ?
        CURR_H db ?

        LAST_READING_TIME dd 11111111h  ; Last scroll time
        TIME_DIFFERENCE  dd 11111111h  ; DIFFERENCE TIME Calculation of time

    ; Keys
    ;------------------------------------
        KeyDown             equ 5000h
        KeyLeft             equ 4B00h
        KeyRight            equ 4D00h
        KeySpaceBar         equ 0020h
   
.code

print_str macro str
   push ax
   push dx
   xor dx, dx
   xor ax, ax
   lea dx, str
   mov ah, 9
   int 21h
   pop dx
   pop ax
endm

PushAXBX macro 
    push AX 
    push BX 
endm

PushAXBXCX macro 
    PushAXBX 
    push CX 
endm

PushAXBXCXDX macro 
    PushAXBXCX
    push DX 
endm
    
PopAXBX macro 
    pop  BX
    pop  AX 
endm

PopAXBXCX macro 
    pop  CX 
    PopAXBX 
endm

PopAXBXCXDX macro 
    pop  DX 
    PopAXBXCX 
endm

;==============================================================================================
;=======================================MY FUNCTIONS===========================================
;==============================================================================================

GENERATE_RANDOM proc ; Return AL
    push BX
    push CX
    push DX

    ; timer interruption (to generate random value)
    mov  AX, 0h
    int  1Ah
    
    mov  AX, DX ; Moves value generated by interrupt to AX. This amount will be divided
    mov  CX, 7h ; Set limit of the number to be generated
    mov  DX, 0h ; Set start number
    div  CX     ; Divide the value of from AX by CX
    mov  AX, DX ; Get the value generated in the rest of the division and put it in AX
    xor  AH, AH ; Removes possible garbage that exists in the upper part

    pop DX
    pop CX
    pop BX
    ret
endp
;----------------------------------------------------------------------------------------------
CHAR_DISPLAY proc  ; Proc that prints on the screen ONE character in a certain color (BL)
    PushAXBXCX
    xor  AH, AH
    xor  CX, CX
    mov  BH , 0
    mov  AH, 09h   ;Interrupt 10h service to print character on screen  
    mov  CX, 01h   ;Number of times the character will be shown on the screen
    int  10h  
    PopAXBXCX
    ret
endp
;----------------------------------------------------------------------------------------------
GOTO_XY proc   ;Proc where the cursor is at a position X [T],Y [BH] AH=02h BH = Page Number, DH = Row, DL = Column 
    push AX  
    xor AX, AX
    mov AH, 2  ;Interrupt service 10h to change cursor position 
    int 10h 
    pop AX
    ret
endp
;----------------------------------------------------------------------------------------------
PUTS_STRING proc ; Proc gets the word, position and color to print on the screen [SI word, DH posx, DL posy, BL color]
    PushAXBXCXDX
    mov  AL, [SI]          ;Points to the string's memory address.
    loop_print_string:
        call GOTO_XY       ;Calls the proc that sets the cursor [x,y]
        cmp AL, ' '
        je skip_char_display
        call CHAR_DISPLAY  ;Calls the proc that prints the colored character on the screen
        skip_char_display:
        inc SI             ;Increment the memory position to the next character
        inc DL             ;Increment the x position on the screen for printing the next character 
        mov AL, [SI]       ;Points to the string's memory address.
        cmp AL, '$'        ;Check if you have reached the end of the string
        jne loop_print_string
    PopAXBXCXDX
    ret
endp
;----------------------------------------------------------------------------------------------
PRINT_GENERIC_FIGURE proc ; SI = offset piece ; HD = part line; DA = part column; BL = part color
  PushAXBXCXDX
  mov CX,4
  .print:
    call PUTS_STRING
    inc DH
    inc SI
    loop .print
  PopAXBXCXDX 
  ret
endp
;----------------------------------------------------------------------------------------------
PRINT_FIGURE proc ; al = number of figure ; ah [0 = write; 1 = erase]
    PushAXBXCXDX
    cmp  AL, 00d ; Figure T
    jne  try_figure_S
        mov BL, 04h            
        mov SI, OFFSET FIGURE_T
        jmp print_figure_now
    try_figure_S:
    cmp  AL, 01d ; Figure S
    jne  try_figure_Z
        mov BL, 06h            
        mov SI, OFFSET FIGURE_S
        jmp print_figure_now
    try_figure_Z:    
    cmp  AL, 02d ; Figure Z
    jne  try_figure_I
        mov BL, 0Eh            
        mov SI, OFFSET FIGURE_Z
        jmp print_figure_now
    try_figure_I:    
    cmp  AL, 03d ; Figure I
    jne  try_figure_O
        mov BL, 02h            
        mov SI, OFFSET FIGURE_I
        jmp print_figure_now
    try_figure_O:    
    cmp  AL, 04d ; Figure O
    jne  try_figure_J
        mov BL, 03h            
        mov SI, OFFSET FIGURE_O
        jmp print_figure_now
    try_figure_J:    
    cmp  AL, 05d ; Figure J
    jne  try_figure_L
        mov BL, 09h            
        mov SI, OFFSET FIGURE_J
        jmp print_figure_now
    try_figure_L:
        mov BL, 01h            
        mov SI, OFFSET FIGURE_L
        jmp print_figure_now

    print_figure_now:
    cmp ah, 1
    jne skip_and_print
    mov bl,0
    skip_and_print:
    mov AX,0
    call PRINT_GENERIC_FIGURE

    PopAXBXCXDX
ret
endp
;----------------------------------------------------------------------------------------------
CLEAR_SCREEN proc  ;This proc clears the user's screen
    PushAXBXCXDX
    MOV   AX,0600h   
    MOV   BH,07      
    MOV   CX,0000    
    MOV   DX,184Fh   
    INT   10H      
       
    ;mov AX, 0620h
    ;mov BX, 0h
    ;mov CX, 0h
    ;mov DX, 1998h
    ;int 10h
    PopAXBXCXDX
    ret
endp
;----------------------------------------------------------------------------------------------
GENERATE_NEXT_FIGURE proc
    PushAXBXCXDX
    mov SI, offset NEXT_FIGURE_NUM
    mov AL, [SI]
    mov AH, 1h
    mov DX, 041Dh
    call PRINT_FIGURE
    
    call GENERATE_RANDOM
    mov  AH, 0h
    call PRINT_FIGURE
    mov SI, offset NEXT_FIGURE_NUM
    mov [SI], AL
    PopAXBXCXDX
ret
endp
;----------------------------------------------------------------------------------------------
;DELAY proc            ;zaderzhka
 ;   PushAXBXCXDX
 ;   MOV AL, 0
 ;   MOV CX, 0FH
 ;   MOV DX, 4240H
 ;   MOV AH, 86H
 ;   INT 15H
 ;   PopAXBXCXDX
;ret
;endp
;----------------------------------------------------------------------------------------------
GET_FIGURE_POSITION proc
    mov SI, offset CURR_W
    mov DH, [SI]
    mov SI, offset CURR_H
    mov DL, [SI]
    mov SI, offset CURR_FIGURE_NUM
    mov AL, [SI]
ret
endp
;----------------------------------------------------------------------------------------------
UPDATE_CURR_POSITION proc
    mov SI, offset CURR_W
    mov [SI], DH
    mov SI, offset CURR_H
    mov [SI], DL
ret
endp
;----------------------------------------------------------------------------------------------
ADD_NEXT_FIGURE proc  ; Add Next Figure on screen
    PushAXBXCXDX
    mov SI, offset NEXT_FIGURE_NUM
    mov AL, [SI]                    ; Get current value and put it in AL
    mov SI, offset CURR_FIGURE_NUM
    mov [SI], AL                    ; Put new part
    mov DL, 10h                     ; Set new position x,y
    mov DH, 2h
    call UPDATE_CURR_POSITION       ; Update current position
    call PRINT_FIGURE               ; Print piece
    PopAXBXCXDX
    call GENERATE_NEXT_FIGURE       ; Generate next play piece
ret
endp
;----------------------------------------------------------------------------------------------
CHECK_COLLISION proc  ; Receives position in DX and checks if tetramino will collide(STOLKNULIS'); Return result in AX
    PushAXBXCXDX
    mov CX,DX                 ; Store received position
    call GET_FIGURE_POSITION   ; Pick Piece and current position
    
    push DX
    mov BX, 20                ; Displacement (offset, "smeschenie")
    mul BX                    ; Take hold through the number * displacement
    mov SI, offset FIGURE_T
    xor AH,AH
    add SI, AX                ; Save figure's address
    pop DX
    check_displacement:
        cmp CH, DH            ; Check if displacement went down
        jne checkBellow 
        cmp CL, DL
        jns checkRight        ; Check if shift("sdvig") was to the left (jns - there is a sign)
        jmp checkLeft         ; Check if shift was to the right
    
    checkBellow:   
        ;mov BX, DX
        ;mov DX, CX
        inc DH
        mov CX, 16            ; Set counter

        innerCheckBellow:
            
            mov AX, [SI]      ; Get the part position value 
            xor AH, AH

            cmp AX, BLOCK     ; Check if part position is a square
            jne innerBellowNoValue  ; If not continue loop

            push AX
            add DH, 2
            sub DL, 3
            call GOTO_XY      ; Position cursor on need(desired) element
            mov AH, 08h       ; Instruction for reading the screen character 
            int 10H 
            mov BX,AX         ; Store read pixel value in BX
            sub DH, 2
            add DL, 3
            call CHAR_DISPLAY
            pop AX
            cmp BH, 0h
            je innerBellowNoValue
            xor BH, BH
            cmp BX, BLOCK
            jne achou 
            innerBellowNoValue:
            inc SI
            inc DL
            cmp [SI], '$'
            jne skipIncLine
            inc DH
            sub DL, 4
            inc SI
            skipIncLine:
        loop innerCheckBellow
        jmp end_check_collision
    checkLeft:
       call GET_FIGURE_POSITION
       push ax
       mov ah, 0ch
       mov al, dl
       inc al
       cmp ah, AL
       je  LeftWall
       jne LeftGood
       LeftWall:
       inc DL
       inc DL
       call UPDATE_CURR_POSITION
       LeftGood:
       pop ax
       jmp end_check_collision 
    
    ;you must add code here
          
    checkRight:    
    
    ;you must add code here
    
    achou:
        mov SI, offset GAME_SCORE
        add [SI], 100
        call PRINT_SCORE
      

    end_check_collision:
    popAXBXCXDX
ret
endp
;----------------------------------------------------------------------------------------------
UPDATE_TIME proc ;Save the current time in the last Time variable
    PushAXBXCXDX
    mov  AX, 0h                     ; Get System-Timer Timer
    int  1Ah                        ; Interruption for work with time

    mov  word ptr LAST_READING_TIME, DX      ; DX = Low-order part of clock count
    mov  word ptr LAST_READING_TIME + 2, CX  ; CX = High-order part of clock count
    PopAXBXCXDX
    ret
endp
;----------------------------------------------------------------------------------------------
CHECK_LAST_TIME proc ;Save in TIME_DIFFERENCE elapsed between the current time and the time saved in LAST_READING_TIME
    PushAXBXCXDX
    mov  AX, 0h
    int  1Ah
    mov  AX, word ptr LAST_READING_TIME
    sub  DX, AX
    mov  word ptr TIME_DIFFERENCE, DX
    mov  AX, word ptr LAST_READING_TIME + 2
    sbb  CX, AX
    mov  word ptr TIME_DIFFERENCE + 2, CX
    PopAXBXCXDX
    mov  AX, word ptr TIME_DIFFERENCE
    ret
endp
;----------------------------------------------------------------------------------------------
CHECK_INPUT proc
    PushAXBXCX
    call UPDATE_TIME
    check_again:
        push AX                 ; Store AX value to be able to read from keyboard
        mov AH, 01h             ; Read the buffer
        mov AL, 00h
        int 16h                 ; Reading interruption
        jz exit_check_input     ; If we don't have anything to read, skip to the end of the loop.
        mov ah, 0               ; Get value from keyboard
        int 16h 
        
        ; Delete Current Figure
        push AX                 ; Stacks read value
        mov SI, offset CURR_FIGURE_NUM ; Get current part number
        mov AX, [SI]
        mov AH, 1               ; Option to write the part in black
        call PRINT_FIGURE       ; Print the piece (as it is black, it will erase from the screen)
        pop AX                  ; Unstack read value
    
        ; Moves the Figure according to the value read on the keyboard
        cmp AX, KeyRight        ; Check if it was right arrow
        je moveRight            
        cmp AX, KeyLeft         ; Check if it was left arrow
        je moveLeft 
        jne exit_check_input ; Did not read valid value, so skips other read checks
        
        moveLeft:
        dec DL                  ; Decrement Column
        call CHECK_COLLISION  
        
        jmp print_figure_check
        
        moveRight:
        inc DL
        call CHECK_COLLISION  


        print_figure_check:
        pop AX
        mov AH,0          ; Option parameter to print colored part
        call PRINT_FIGURE ; Print Piece
        call UPDATE_CURR_POSITION
        jmp exit_check_input_2

        exit_check_input:    
        pop AX            ; Returns original AX value before keyboard reading
        
        exit_check_input_2:
        push AX
        call CHECK_LAST_TIME
        mov CX, AX
        pop AX
        cmp  CX, 0Fh
        jna  check_again

    PopAXBXCX
ret
endp
;----------------------------------------------------------------------------------------------
DOWN_LINE proc
    ; Delete Figure
    mov AH,1
    call PRINT_FIGURE

    ; Line down
    inc DH

    ;call CHECK_COLLISION

    ; Increment Score
    mov SI, offset GAME_SCORE
    inc [SI]
    call PRINT_SCORE 
    
    ; Print Figure
    mov AH,0
    call PRINT_FIGURE
    call UPDATE_CURR_POSITION
    call UPDATE_TIME  
ret
endp
;----------------------------------------------------------------------------------------------
PRINT_SCORE proc
    PushAXBXCXDX
    mov DH, 02h                     ; Adjust(regulirovat') Line 
    mov DL, 0Ah                     ; Adjust Column (4 + 6) -> The value will also be used as a divisor
    mov BL, 06h                     ; Set minimum limit of characters 
    mov CX, word ptr GAME_SCORE
    
    DIGITAL_SCORE_LOOP:
        mov  AX, CX
        push DX
        mov  DX, 0h
        mov  CX, 0Ah                ; Set the divisor value = 10
        div  CX                     ; Divide AX by CX
        mov  CX, AX                 ; Save result value in CX
        mov  AX, DX                 ; Take the result of division and store it in AX
        add  AL, '0'                ; Add '0' to print correct character
        pop  DX

        ; Print Value on Screen
        push CX                  
        mov CX,1                    ; Informs that there is only one character to be displayed
        sub DX,2       
        call GOTO_XY                ; Go to position
        call CHAR_DISPLAY           ; Prints
        add DX,2
        pop CX
        cmp  DL, BL
        je   END_PRINT_SCORE
        dec  DL
    jmp  DIGITAL_SCORE_LOOP
    
    END_PRINT_SCORE:          
    popAXBXCXDX       
    ret  
endp
;----------------------------------------------------------------------------------------------
GAME_SCREEN proc
    PushAXBXCXDX   
    call CLEAR_SCREEN
    
    ; Displays Score
    mov  word ptr GAME_SCORE, 0
    call PRINT_SCORE    
    
    ; Display Score(String)
    mov SI, offset SCORE_MSG
    mov DH, 01h
    mov DL, 04h
    mov BL, 07h  
    call PUTS_STRING  
    
    ; Top Line of the Game
    ;-------------------------------   
    mov DX, 010Ch
    call GOTO_XY
    print_str GAME_FIELD_GORIZONT
    
    ; Side Lines Game
    mov CX,16h
    mov DX,010Ch        
    LOOP_SCREEN_GAME:
        inc DH
        call GOTO_XY
        print_str GAME_SIDE_VERTICAL
    loop LOOP_SCREEN_GAME
                        
    ; Bottom Line of the Game
    mov DX, 170Ch
    call GOTO_XY
    print_str GAME_FIELD_GORIZONT
    
    ; Print Next Figure Box
    ;-------------------------------    
    mov  SI, offset PIECE_BOX_BASE
    mov  DX, 011Bh
    call GOTO_XY
    print_str PIECE_BOX_BASE
   
    mov CX,06h
    LOOP_SCREEN_BOX:
    mov  SI, offset PART_BOX_SIDE
        inc DH  
        call GOTO_XY
        print_str PART_BOX_SIDE 
    loop LOOP_SCREEN_BOX
    
    mov DH, 08h
    call GOTO_XY
    print_str PIECE_BOX_BASE
    
    ; Print First Piece
    ;-------------------------------
    call GAMEPLAY
    PopAXBXCXDX
    ret
endp
;----------------------------------------------------------------------------------------------
GAMEPLAY proc
    call GENERATE_NEXT_FIGURE 
    ;call DELAY
    loop_game:
    call ADD_NEXT_FIGURE
    call GET_FIGURE_POSITION

    mov CX,20d
    loop_falling_figure:
        call UPDATE_TIME
        call DOWN_LINE 
        call CHECK_INPUT  

    loop loop_falling_figure
    jmp loop_game
ret
endp
;----------------------------------------------------------------------------------------------
HOME_SCREEN proc
   PushAXBXCXDX
   ;call CLEAR_SCREEN                                ;this line was commented by me.
 
   ; Displays home screen to user
   mov SI, offset TETRIS ; Title
   mov BL, 02h           ; Color
   mov DH, 05h           ; Line, y
   mov DL, 0Bh           ; Column, x
   call PUTS_STRING
  
   ; Displays Tetrafigures
   mov DH, 09h ; starting line
   mov DL, 05h ; starting column
   mov AX, 00h ; starting tetramine
   mov CX, 7
   tetrafigures_menu_loop:
    call PRINT_FIGURE
    add DL, 04
    inc AL
   loop tetrafigures_menu_loop

   ; Play Option 
   mov SI, offset PLAY 
   mov BL, 0Fh
   mov DH, 0Fh 
   mov DL, 0Fh ; 15
   ;call PUTS_STRING
   
   call GOTO_XY
   print_str PLAY
   
   
   ; Exit Option
   mov SI, offset EXIT 
   mov DH, 11h ;17
   mov DL, 0Fh ; 15
   ;call PUTS_STRING
   
   call GOTO_XY
   print_str EXIT

 
   ; Message Developers
   mov SI, offset DESIGN 
   mov BL, 04h
   mov DH, 016h ;22
   mov DL, 0h
   call PUTS_STRING
   
   ; Reads the user to enter or exit the game
   OPTION_MENU:
       mov AX, 0h
       int 16h 
       cmp    AL, 'S'
       je     START_GAME
       cmp    AL, 's'
       je     START_GAME
       cmp    AL, 'E'  
       je     FINISH
       cmp    AL, 'e'
       je     FINISH  
   loopne OPTION_MENU

   START_GAME:
       call GAME_SCREEN
   FINISH:
       call OUTPUT_SCREEN  
   PopAXBXCXDX
   ret
endp
;----------------------------------------------------------------------------------------------
GAME_OVER proc
    PushAXBXCXDX
    call CLEAR_SCREEN
    
    mov SI, offset GAME  
    mov BL, 0Ch
    mov DX, 050Fh
    call PUTS_STRING
    
    mov SI, offset OVER  
    mov BL, 0Ch
    mov DX, 0A0Fh 
    call PUTS_STRING
    
    mov SI, offset PLAY ; Option to play
    mov BL, 0Fh
    mov DX, 0F0Fh 
    call PUTS_STRING
  
    mov SI, offset EXIT ; Option to exit
    mov DX, 110Fh 
    call PUTS_STRING
   
    OPTION_MENU2:
        mov AX, 0h
        int 16h 
        cmp AL, 'S'
        je START_GAME_2
        cmp AL, 's'
        je START_GAME_2
        cmp AL, 'E'  
        je FINISH_2
        cmp AL, 'e'
        je FINISH_2  
        loopne OPTION_MENU2

        START_GAME_2:
            call GAME_SCREEN
            loopne OPTION_MENU2
        FINISH_2:
            call OUTPUT_SCREEN

    PopAXBXCXDX
ret
endp
;----------------------------------------------------------------------------------------------
OUTPUT_SCREEN proc
    PushAXBXCXDX
    call CLEAR_SCREEN
   
    ;Goodbye message
    mov SI, offset THANKS  
    mov BL, 04h             ;color
    mov DX, 050Bh           ;coordinates
    call PUTS_STRING
    
    inc SI
    mov BL, 02h             ;color
    mov DX, 0A09h           ;coordinates
    call PUTS_STRING
   
    mov SI, offset TETRIS 
    mov BL, 0Eh             ;color
    mov DX, 0F0Bh           ;coordinates
    call PUTS_STRING
   
    mov AL, 01h
    mov BL, 02h
    mov DX, 1205h 
    show_smiley_faces: 
        call GOTO_XY
        call CHAR_DISPLAY
        add DL, 2h
        inc BL
        cmp DL, 21h
        jne show_smiley_faces
    PopAXBXCXDX
ret
endp
        
;==============================================================================================
;=======================================MAIN FUNCTION==========================================
;==============================================================================================

MAIN:                 ;Start of the program                   
    mov AX, @DATA
    mov DS, AX
    
    mov AX, 0b800h    ;Put the video memory adress in ES
    mov ES, AX
       
    mov AH, 00h       ;Set video mode
    mov AL, 01h       ;Set 40x25 standart 16-color text mode
    int 10h 
   
    call HOME_SCREEN
    
    ;call GAME_OVER
    
    mov AX, 4c00h     ;Program completion, exit
    int 21h

end MAIN